# Generated by Django 2.1.7 on 2019-03-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewprep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lessonCount',
            new_name='lesson_count',
        ),
    ]
