# Generated by Django 2.1.7 on 2019-03-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewprep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
