# Generated by Django 2.1.7 on 2019-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewprep', '0002_auto_20190318_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='speechtext',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='visemes',
            field=models.CharField(max_length=500),
        ),
    ]
