# Generated by Django 2.1.7 on 2019-03-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='graduationyear',
            new_name='graduation_year',
        ),
    ]
